#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' Styling, Testing and Building your project before commiting';

# Check Prettier
npm run check-format || 
(
    # misalkan ada error jika ada kodingan yang tidak sesuai dengan prettier
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again';
    false;
)

# Check Eslint
npm run check-lint ||
(
    echo 'Eslint Check Failed, Make the required changes listed above, add changes and try to commit again';
    false;
)

# Check tsconfig
npm run check-types ||
(
    echo 'Failed type check. Make the changes requir above, add changes and try to commit again';
    false;
)

npm run build ||
(
    echo "Your build faield. view the error above";
    false;
)


echo "Success Commit";
